enum ClientEvent {
  JOINED_TO_ROOM = 'JOINED_TO_ROOM',
  UPDATED_ROOM = 'UPDATED_ROOM',
  SELECTED_CARD = 'SELECTED_CARD',
  MODIFIED_ROOM_ISSUE = 'MODIFIED_ROOM_ISSUE',
  ERROR = 'ERROR',
  USER_JOINED_TO_ROOM = 'USER_JOINED_TO_ROOM',
  USER_LEFT_ROOM = 'USER_LEFT_ROOM',
  USER_KICKED_FROM_ROOM = 'USER_KICKED_FROM_ROOM'
}

export default ClientEvent
