enum ServerEvent {
  CREATE_ROOM = 'CREATE_ROOM',
  JOIN_ROOM = 'JOIN_ROOM',
  LEAVE_ROOM = 'LEAVE_ROOM',
  SELECT_CARD = 'SELECT_CARD',
  REVEAL_CARDS = 'REVEAL_CARDS',
  RESET_ROOM = 'RESET_ROOM',
  SET_ROOM_ISSUE = 'SET_ROOM_ISSUE',
  PROMOTE_ROOM_USER = 'PROMOTE_ROOM_USER',
  DEMOTE_ROOM_USER = 'DEMOTE_ROOM_USER',
  KICK_ROOM_USER = 'KICK_ROOM_USER'
}

export default ServerEvent
